language: node_js
node_js:
  - '10'
install:
  - npm install

# before_script:
  # - npm run test
script:
  - npm run build
after_success:
  - npm run release
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master