language: node_js
node_js:
  - '10'
install:
  - npm install
script:
  - npm test -- --coverage
  - npm run build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls
after_success:
  - npm run release
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master